defaults: base_qwen1b_squad.yaml

policy:
  dtensor_cfg:
    tensor_parallel_size: 2
  make_sequence_length_divisible_by: 2

logger:
  wandb:
    name: "sft-qwen1b-squad-dtensor-tp2-8gpu"
  tensorboard:
    log_dir: "tb_logs-token-accuracy-dtensor-tp2-8gpu"

cluster:
  gpus_per_node: 8
