# SFT Algorithm Configuration
defaults: sft_openmathinstruct2.yaml

sft:
  max_num_epochs: 1
  max_num_steps: 1000000
  val_period: 500
  val_batches: 4
  val_global_batch_size: 128
  val_micro_batch_size: 1
  val_at_start: false
  val_at_end: false
  seed: 42

checkpointing:
  enabled: true
  checkpoint_dir: "results/sft_openmathinstruct2_megatron_30b"
  metric_name: "val:val_loss" # one of "val:" or "train:" followed by the metric name
  higher_is_better: false
  keep_top_k: 1
  save_period: 500

policy:
  model_name: "Qwen/Qwen3-30B-A3B-Base"
  tokenizer:
    name: Qwen/Qwen3-30B-A3B-Base
  train_global_batch_size: 512
  train_micro_batch_size: 2
  max_total_sequence_length: 4096
  precision: "bfloat16"

  dtensor_cfg:
    enabled: false

  megatron_cfg:
    activation_checkpointing: false
    context_parallel_size: 1
    distributed_data_parallel_config:
      data_parallel_sharding_strategy: optim_grads_params
      grad_reduce_in_fp32: true
      overlap_grad_reduce: true
      overlap_param_gather: true
      use_custom_fsdp: false
    empty_unused_memory_level: 0
    enabled: true
    expert_tensor_parallel_size: 1
    expert_model_parallel_size: 8
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    optimizer:
      adam_beta1: 0.9
      adam_beta2: 0.98
      adam_eps: 1.0e-8
      bf16: true
      clip_grad: 1.0
      fp16: false
      lr: 5.0e-5
      min_lr: 1.0e-7
      optimizer: adam
      params_dtype: bfloat16
      sgd_momentum: 0.9
      # These reduce optimizer memory by ~50%:
      use_distributed_optimizer: true
      use_precision_aware_optimizer: true ## TODO: precision aware optim not working with fp8. Is this expected?
      main_params_dtype: float32       # keep master weights in FP32
      main_grads_dtype: bfloat16
      exp_avg_dtype: bfloat16
      exp_avg_sq_dtype: bfloat16

      weight_decay: 0.01
      

      # optimizer cpu offload
      optimizer_cpu_offload: false
      optimizer_offload_fraction: 0.0

      ## recently introduced, our current mcore commit doesn't have this
      #fp8_recipe: delayed

    pipeline_dtype: bfloat16
    pipeline_model_parallel_size: 1
    scheduler:
      end_weight_decay: 0.01
      lr_decay_iters: null #1000
      lr_decay_style: cosine
      lr_warmup_init: 0. # 2.0e-6
      lr_warmup_iters: 50
      start_weight_decay: 0.01
      weight_decay_incr_style: constant
    sequence_parallel: false
    tensor_model_parallel_size: 1

    freeze_moe_router: false
    moe_router_topk: 8
    moe_router_dtype: "fp32"
    moe_router_load_balancing_type: "aux_loss"
    moe_aux_loss_coeff: 0.1
    moe_router_bias_update_rate: 0.001
    moe_permute_fusion: true
    apply_rope_fusion: true
    bias_activation_fusion: true
    moe_per_layer_logging: false
    moe_enable_deepep: false # true #
    moe_token_dispatcher_type: "alltoall" # "flex" #
    moe_shared_expert_overlap: false
    defer_fp32_logits: true

    env_vars:
      PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:True"

    fp8_cfg:
      enabled: false
      fp8: "e4m3"
      fp8_recipe: "blockwise"
      fp8_param: false

  dynamic_batching:
    enabled: false
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    sequence_length_round: 64


  sequence_packing:
    enabled: True
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    algorithm: "modified_first_fit_decreasing"
    sequence_length_round: 64

  # makes the training sequence length divisible by the tensor parallel size
  # this is useful for sequence parallel training
  make_sequence_length_divisible_by: ${mul:16, ${policy.megatron_cfg.tensor_model_parallel_size}}
  max_grad_norm: null

  optimizer: null

data:
  num_workers: 1

logger:
  log_dir: "logs"  # Base directory for all logs
  wandb_enabled: true # Make sure you do a ``wandb login [Your API key]'' before running
  tensorboard_enabled: true
  mlflow_enabled: false
  monitor_gpus: true  # If true, will monitor GPU usage and log to wandb and/or tensorboard
  wandb:
    project: "sft-openmathinstruct-megatron"
    name: "qwen30b-a3b-sft"
  tensorboard:
    enabled: false
  mlflow:
    experiment_name: "sft-dev"
    run_name: "openmathinstruct-nemorl-1M_train"
  gpu_monitoring:
    collection_interval: 10  # How often to collect GPU usage metrics (in seconds)
    flush_interval: 10  # How often to flush GPU usage metrics to the loggers (in seconds)

cluster:
  gpus_per_node: 8
  num_nodes: 1
                                                  
